{{- if and (not .Values.adminToken.existingSecret) .Values.adminToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distil-gateway.fullname" . }}-admin
  labels: {{- include "distil-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.adminToken.existingSecretKey }}: {{ .Values.adminToken.value | quote }}
{{- end }}
