#!/usr/bin/env python3
"""Render the agent-coverage tables in README.md and docs/ from the code.

``distil.targets.catalog()`` is the one source of truth for which agents
``distil wrap`` reaches, how, and which wire shape the proxy speaks for each.
Three documents used to restate that by hand and all three drifted: the README
advertised a preset count that stopped matching the registry, IDE-AGENTS.md
called Warp "no published base-URL override at all" a release after Warp
shipped one, and integrations.html listed Mistral Vibe as unreachable after it
became a preset.

So each document keeps a marker-fenced region per table and this script
rewrites what is between the markers. Everything outside them — the prose that
actually explains the mechanism — stays hand-written.

Usage:
    python3 scripts/build_agent_tables.py           # rewrite in place
    python3 scripts/build_agent_tables.py --check   # exit 1 if anything is stale

``tests/test_wrap_targets.py`` runs --check, so a preset added without
refreshing the docs fails the suite rather than shipping a stale table.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from distil.targets import Target, catalog  # noqa: E402


def _begin(name: str) -> str:
    return f"<!-- BEGIN {name} (generated by scripts/build_agent_tables.py) -->"


def _end(name: str) -> str:
    return f"<!-- END {name} -->"


def replace_region(text: str, name: str, body: str) -> str:
    """Swap the content between ``name``'s markers. Missing markers are an
    error, not a silent no-op — that is how a generated table quietly stops
    being generated."""
    start, stop = _begin(name), _end(name)
    if start not in text or stop not in text:
        raise SystemExit(f"marker {name!r} not found — add {start} / {stop} to the document")
    head, rest = text.split(start, 1)
    _stale, tail = rest.split(stop, 1)
    return f"{head}{start}\n{body.rstrip()}\n{stop}{tail}"


# ---------------------------------------------------------------------------
# Renderers. One per region; each takes the catalogue and returns markup.
# ---------------------------------------------------------------------------


def _wrappable(targets: list[Target]) -> list[Target]:
    return [t for t in targets if t.wrappable]


def readme_bullet(targets: list[Target]) -> str:
    env = [t for t in targets if t.mechanism == "env"]
    cfg = [t for t in targets if t.mechanism == "config"]
    names = " · ".join(f"`{t.key}`" for t in env + cfg)
    return (
        f"- **Wrap your agent** — {len(env) + len(cfg)} presets: `distil wrap -- <agent>` for "
        f"{names}. Zero config, no code change. `distil wrap --list` prints every target, its "
        f"mechanism and the provider shape it speaks."
    )


def readme_presets_line(targets: list[Target]) -> str:
    env = [t.key for t in targets if t.mechanism == "env"]
    cfg = [t.key for t in targets if t.mechanism == "config"]
    return (
        f"Each recognized agent auto-selects the right env var and upstream — no `--env-var` or "
        f"`--upstream` flag needed. {len(env)} route through an environment variable "
        f"(`{'` / `'.join(env)}`); {len(cfg)} have no env-var contract at all and route through a "
        f"config file `wrap` manages for the session and restores on exit "
        f"(`{'` / `'.join(cfg)}`). Prints `preset: <agent> detected → <VAR>` on start. Explicit "
        f"flags always win."
    )


def _md_table(rows: list[tuple[str, ...]], header: tuple[str, ...]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def ide_wrappable_table(targets: list[Target]) -> str:
    rows = [
        (
            f"**{t.label}**",
            f"`distil wrap -- {t.key}`",
            "env var" if t.mechanism == "env" else f"config file ({t.note})",
            f"`{t.knob}`",
            f"[source]({t.doc_url}) ({t.verified})",
        )
        for t in _wrappable(targets)
    ]
    return _md_table(rows, ("Agent", "Command", "Mechanism", "Routing knob", "Verified"))


def ide_unreachable_table(targets: list[Target]) -> str:
    rows = [
        (
            f"**{t.label}**",
            t.knob,
            t.note,
            f"[source]({t.doc_url}) ({t.verified})",
        )
        for t in targets
        if not t.wrappable
    ]
    return _md_table(rows, ("Agent", "Its own base-URL setting", "Why `wrap` cannot", "Verified"))


def _html_rows(rows: list[tuple[str, ...]]) -> str:
    return "\n".join("        <tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)


def integrations_wrappable(targets: list[Target]) -> str:
    return _html_rows(
        [
            (
                f"<strong>{html.escape(t.label)}</strong>",
                f"<code>distil wrap -- {html.escape(t.key)}</code>",
                "environment variable" if t.mechanism == "env" else "config file",
                f"<code>{html.escape(t.knob)}</code>",
                f"{html.escape(t.shape)}",
            )
            for t in _wrappable(targets)
        ]
    )


def integrations_unreachable(targets: list[Target]) -> str:
    return _html_rows(
        [
            (
                f"<strong>{html.escape(t.label)}</strong>",
                f"<code>{html.escape(t.knob)}</code>",
                html.escape(t.note),
                f'<a href="{html.escape(t.doc_url)}">verified {html.escape(t.verified)}</a>',
            )
            for t in targets
            if not t.wrappable
        ]
    )


#: document -> {region name: renderer}
REGIONS = {
    "README.md": {
        "agent-presets-bullet": readme_bullet,
        "agent-presets-line": readme_presets_line,
    },
    "docs/IDE-AGENTS.md": {
        "agent-wrappable-table": ide_wrappable_table,
        "agent-unreachable-table": ide_unreachable_table,
    },
    "docs/integrations.html": {
        "agent-wrappable-rows": integrations_wrappable,
        "agent-unreachable-rows": integrations_unreachable,
    },
}


def render(root: Path = ROOT) -> dict[Path, str]:
    """The content every managed document SHOULD have, keyed by path."""
    targets = catalog()
    out: dict[Path, str] = {}
    for rel, regions in REGIONS.items():
        path = root / rel
        text = path.read_text(encoding="utf-8")
        for name, fn in regions.items():
            text = replace_region(text, name, fn(targets))
        out[path] = text
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    stale = []
    for path, wanted in render().items():
        if path.read_text(encoding="utf-8") == wanted:
            continue
        stale.append(path.name)
        if not check:
            path.write_text(wanted, encoding="utf-8")
    if not stale:
        print("agent tables in sync")
        return 0
    if check:
        print("agent tables out of sync on: " + ", ".join(stale))
        print("run: python3 scripts/build_agent_tables.py")
        return 1
    print("rewrote: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
